language: java
jdk:
  - oraclejdk8

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: 
    - "target/*-generated-artifacts.zip"
    - "target/*-generated-artifacts.tar.gz"
  skip_cleanup: true
  on:
    tags: true
