sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    cd target
    docker build -t hotstepper13/alexa-gira-bridge:latest .
    docker push hotstepper13/alexa-gira-bridge:latest;
    elif [ -n "$TRAVIS_TAG" ]; then
    cd target
    docker build -t hotstepper13/alexa-gira-bridge:$TRAVIS_TAG .
    docker push hotstepper13/alexa-gira-bridge:$TRAVIS_TAG;
    fi

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: 
    - "target/gira-bridge-generate-artifacts.tar.gz"
    - "target/gira-bridge-generate-artifacts.zip"
  skip_cleanup: true
  on:
    tags: true
